### ISSUE TITLE
1

### ISSUE THREAD

**Issue by JMSTV** [239144498/Streaming-Media-Server-Pro#10]
1

**Comment by kfcx** [comment]
> 大佬有没有意愿加入我们公益团队，目前我们有很多程序员大佬，可以提供一切你需要的资源，从服务器、全球知名流媒体会员到各种福利等等，把github开源精神和公益分享精神发扬光大。tg搜Curly_MouseIPTV就是我们

很感谢你的邀请，我很乐意做更多的开源项目；但是迫于学业压力，现在需要把更多时间投入到其中。

**Comment by JMSTV** [comment]
> > 大佬有没有意愿加入我们公益团队，目前我们有很多程序员大佬，可以提供一切你需要的资源，从服务器、全球知名流媒体会员到各种福利等等，把github开源精神和公益分享精神发扬光大。tg搜Curly_MouseIPTV就是我们
> 
> 很感谢你的邀请，我很乐意做更多的开源项目；但是迫于学业压力，现在需要把更多时间投入到其中。

好的 ，明白 ，那我可以加你下微信吗 ？不方便的话你也可以加我 交个朋友 微信号：mediacentero
