### ISSUE TITLE
程序运行后大量占用CPU 内存 带宽资源 导致宕机

### ISSUE THREAD

**Issue by qupaif** [239144498/Streaming-Media-Server-Pro#13]
程序运行后大量占用CPU 内存 带宽资源 导致宕机，望修复
![image](https://user-images.githubusercontent.com/45931822/191668828-42983e3b-e56b-4eda-8161-9e7cdd7442f4.png)

**Comment by 239144498** [comment]
> 程序运行后大量占用CPU 内存 带宽资源 导致宕机，望修复 ![image](https://user-images.githubusercontent.com/45931822/191668828-42983e3b-e56b-4eda-8161-9e7cdd7442f4.png)

使用 ps -aux 命令查看程序占用

**Comment by kfcx** [comment]
> > 程序运行后大量占用CPU 内存 带宽资源 导致宕机，望修复 ![image](https://user-images.githubusercontent.com/45931822/191668828-42983e3b-e56b-4eda-8161-9e7cdd7442f4.png)
> 
> 使用 ps -aux | grep python 命令查看程序占用

**Comment by qupaif** [comment]
> > > 程序运行后大量占用CPU 内存 带宽资源 导致宕机，望修复 ![image](https://user-images.githubusercontent.com/45931822/191668828-42983e3b-e56b-4eda-8161-9e7cdd7442f4.png)
> > 
> > 
> > 使用 ps -aux | grep python 命令查看程序占用

docker 部署的

**Comment by kfcx** [comment]
> > > > 程序运行后大量占用CPU 内存 带宽资源 导致宕机，望修复 ![image](https://user-images.githubusercontent.com/45931822/191668828-42983e3b-e56b-4eda-8161-9e7cdd7442f4.png)
> > > 
> > > 
> > > 使用 ps -aux | grep python 命令查看程序占用
> 
> docker 部署的

ps -aux | grep docker

**Comment by qupaif** [comment]
> > > > > 程序运行后大量占用CPU 内存 带宽资源 导致宕机，望修复 ![image](https://user-images.githubusercontent.com/45931822/191668828-42983e3b-e56b-4eda-8161-9e7cdd7442f4.png)
> > > > 
> > > > 
> > > > 使用 ps -aux | grep python 命令查看程序占用
> > 
> > 
> > docker 部署的
> 
> ps -aux | grep docker

![1663838904543](https://user-images.githubusercontent.com/45931822/191711572-a5fd3aaa-ed01-4a63-87b8-fc4232ccb301.jpg)
![1663838926239](https://user-images.githubusercontent.com/45931822/191711609-1070fe7e-7d41-4850-a55a-fe0b6602a6b9.jpg)

**Comment by kfcx** [comment]
> 

图片显示docker占用并不高，我这边试了低配置服务器运行也没问题；你可以使用top查看高占用程序将它kill掉

**Comment by qupaif** [comment]
> > 
> 
> 图片显示docker占用并不高，我这边试了低配置服务器运行也没问题；你可以使用top查看高占用程序将它kill掉

uvicorn 这个占用很高，程序运行起来不去播放没事 点击播放就会带宽内存 cpu冲高

**Comment by deskmonster** [comment]
> > 
> 
> 图片显示docker占用并不高，我这边试了低配置服务器运行也没问题；你可以使用top查看高占用程序将它kill掉

docker不是虚拟机，docker里运行的程序在宿主机里用ps 的话会单独列出来程序名称的，不会记录在docker占用里
