### ISSUE TITLE
关于接口突然无法访问原因

### ISSUE THREAD

**Issue by 239144498** [239144498/Streaming-Media-Server-Pro#14]
## 即刻起不再免费提供频道，需要IPTV源可以联系邮箱[239144498@qq.com](mailto:239144498@qq.com)

**Comment by redrainl** [comment]
用python和docker都成功部署过了，用下来体验很好。想问一下台湾ip依赖性的问题：上面提到需要台湾ip，又说如果不想有接口限制，可以自行部署。但我自行部署没使用台湾ip也能正常使用，是说程序依赖于作者的台湾ip服务器提供的接口吗，如果那台机器宕了，自行部署的也就同样不能用了？想问这个，是为了便于当自行部署的使用出现异常时排查问题原因。
