### ISSUE TITLE
收费频道都挂掉了。。

### ISSUE THREAD

**Issue by lck1115** [239144498/Streaming-Media-Server-Pro#16]
4gtv 的收费频道都挂了。。
免费的还可以看。

**Comment by lck1115** [comment]
检测了下，只有7个台可以看，其他全部挂了。。

**Comment by kfcx** [comment]
> 检测了下，只有7个台可以看，其他全部挂了。。

大幅增加每日额度后，每日收到的请求翻了好几倍，现在服务器ip被封用不了
