### ISSUE TITLE
公益接口功能关闭通知

### ISSUE THREAD

**Issue by 239144498** [239144498/Streaming-Media-Server-Pro#17]
## **因为放开接口的每日使用限制，从而服务器ip请求4gtv接口的数量过大，导致现在接口失效，现在我已经没有可用的台湾ip，如果有人愿意分享（联系邮箱239144498@qq.com），才能延续公益接口的正常使用。**

_**如果要继续使用接口，请自行部署。
特别说明：4gtv有ip请求限制，需要台湾ip才能请求成功。**_

**Comment by lck1115** [comment]
我可以提供台湾vps，免费供使用。
但是经过我自己搭建测试，应该跟IP没关系，是官方升级了接口。
给你发邮件了。

**Comment by 239144498** [comment]
感谢上面兄弟提供的设施支持，现在接口都已恢复运行
