### ISSUE TITLE
用docker部署的，底层是ubt，运行不起来

### ISSUE THREAD

**Issue by await777** [239144498/Streaming-Media-Server-Pro#19]
看您教程里写的Python和Docker二选一安装，我在ubt的docker上安装的：
docker pull 239144498/streaming
docker images
docker run -itd -v /home/assets:/code/app/assets -p 8080:8080 --restart=always --name server （这里输入上一步的IMAGE_ID）
http://ip:8080/docs
浏览器打开访问不了呢

**Comment by kfcx** [comment]
> 

http://ip:8080/docs 例如 http://192.168.1.100/docs , 检查是否开放端口,可以用内网试试

**Comment by kfcx** [comment]
拉取最新版docker镜像，已对程序多处更新

**Comment by kfcx** [comment]
如果出现报错提示no section 'redis'，查看教程https://www.cnblogs.com/1314h/p/16651157.html
