### ISSUE TITLE
updateonline函数报错

### ISSUE THREAD

**Issue by jin38324** [239144498/Streaming-Media-Server-Pro#22]
后端日志app.api.a4gtv.utile:updateonline 报错
经过排查，是因为第70行
`cur.setex(fid, last - start, str([url, last, start, seq, gap]))`
第二个参数需要是整数，但是`start`是小数，导致`last - start`也是小数，导致报错。
修改为
`cur.setex(fid, int(last - start), str([url, last, start, seq, gap]))`
解决了报错问题

**Comment by kfcx** [comment]
谢谢反馈，已修改bug
