### ISSUE TITLE
请问proxy接口是否支持代理有用户名密码验证的m3u8

### ISSUE THREAD

**Issue by zhuxiaole** [239144498/Streaming-Media-Server-Pro#28]
大大，你好，如题，请问是否支持？

**Comment by kfcx** [comment]
你好，请问你指的是哪种请求格式？如果是`http://example.com?username=username&password=password`这种格式是可以的

**Comment by zhuxiaole** [comment]
> 你好，请问你指的是哪种请求格式？如果是`http://example.com?username=username&password=password`这种格式是可以的

不是这种，是需要在header中添加Authorization "Basic aGthbmltZTpoa2FuaW1l"
这种的

**Comment by kfcx** [comment]
不支持
