### ISSUE TITLE
請問一直報錯 是否是演算法改變了？無法使用了？

### ISSUE THREAD

**Issue by charles0568** [239144498/Streaming-Media-Server-Pro#31]
WARNING   2022-11-24 04:29:56.178 - app.plugins.a4gtv.utile:updateonline - 未获得数据
WARNING   2022-11-24 04:29:56.179 - app.plugins.a4gtv.utile:updateonline - 405, https://stream.naihe.cf/api/v2/channel2.m3u8?fid=4gtv-4gtv003&type=v3, {"code":405,"msg":"请求成功","data":"4gtv-4gtv003 频道暂不可用，请过 3363.18107008934 秒 后重试"}
INFO:     192.168.1.1:40030 - "GET /channel.m3u8?fid=4gtv-4gtv003&hd=1080 HTTP/1.1" 406 Not Acceptable
INFO:     192.168.1.1:40034 - "GET /channel.m3u8?fid=4gtv-4gtv003&hd=1080 HTTP/1.1" 405 Method Not Allowed
INFO:     192.168.1.1:40036 - "GET /channel.m3u8?fid=4gtv-4gtv003&hd=1080 HTTP/1.1" 405 Method Not Allowed
INFO:     192.168.1.1:40038 - "GET /channel.m3u8?fid=4gtv-4gtv003&hd=1080 HTTP/1.1" 405 Method Not Allowed
SUCCESS   2022-11-24 04:30:00.003 - app.plugins.a4gtv.tasks:filetask - 成功删除视频文件0个
INFO:     192.168.1.1:40042 - "GET /channel.m3u8?fid=4gtv-4gtv003&hd=1080 HTTP/1.1" 405 Method Not Allowed
INFO:     192.168.1.1:40044 - "GET /channel.m3u8?fid=4gtv-4gtv003&hd=1080 HTTP/1.1" 405 Method Not Allowed
SUCCESS   2022-11-24 04:30:03.274 - app.plugins.a4gtv.endecrypt:get4gtvurl - 4gtv-4gtv001 405
WARNING   2022-11-24 04:30:03.276 - app.plugins.a4gtv.utile:updateonline - 未获得数据
WARNING   2022-11-24 04:30:03.277 - app.plugins.a4gtv.utile:updateonline - 405, https://stream.naihe.cf/api/v2/channel2.m3u8?fid=4gtv-4gtv001&type=v3, {"code":405,"msg":"请求成功","data":"4gtv-4gtv001 频道暂不可用，请过 5364.891244649887 秒后重试"}
INFO:     192.168.1.1:40046 - "GET /channel.m3u8?fid=4gtv-4gtv001&hd=1080 HTTP/1.1" 406 Not Acceptable
INFO:     192.168.1.1:40048 - "GET /channel.m3u8?fid=4gtv-4gtv001&hd=1080 HTTP/1.1" 405 Method Not Allowed
INFO:     192.168.1.1:40054 - "GET /channel.m3u8?fid=4gtv-4gtv001&hd=1080 HTTP/1.1" 405 Method Not Allowed
INFO:     192.168.1.1:40056 - "GET /channel.m3u8?fid=4gtv-4gtv001&hd=1080 HTTP/1.1" 405 Method Not Allowed
SUCCESS   2022-11-24 04:30:12.536 - app.plugins.a4gtv.endecrypt:get4gtvurl - 4gtv-4gtv004 405
WARNING   2022-11-24 04:30:12.539 - app.plugins.a4gtv.utile:updateonline - 未获得数据
WARNING   2022-11-24 04:30:12.541 - app.plugins.a4gtv.utile:updateonline - 405, https://stream.naihe.cf/api/v2/channel2.m3u8?fid=4gtv-4gtv004&type=v3, {"code":405,"msg":"请求成功","data":"4gtv-4gtv004 频道暂不可用，请过 6928.372947692871 秒后重试"}

**Comment by charles0568** [comment]
目前又可以用了～

**Comment by kfcx** [comment]
下一个版本将修复该问题

**Comment by charles0568** [comment]
非常感謝您～

**Comment by kfcx** [comment]
新版本已发布

**Comment by charles0568** [comment]
哇～感謝～馬上來更新

**Comment by charles0568** [comment]
請問DOCKER也更新了嗎？

**Comment by charles0568** [comment]
[notice] A new release of pip available: 22.3 -> 22.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip

C:\temp\Streaming-Media-Server-Pro>python main.py
2022-11-26 18:42:03.023 | INFO     | app.conf.config:<module>:67 - 配置加载中...
.-9
...
2022-11-26 18:42:08.030 | INFO     | app.conf.config:<module>:147 - 配置加载完成
2022-11-26 18:42:08.240 | INFO     | app.db.DBtools:<module>:15 - 正在检测数据库连接状态...
2022-11-26 18:42:09.250 | WARNING  | app.db.DBtools:connect_redis:34 - redis连接失败
2022-11-26 18:42:09.251 | WARNING  | app.db.DBtools:<module>:65 - defaultdb未配置mysql
2022-11-26 18:42:09.252 | SUCCESS  | app.plugins.a4gtv.utile:init:44 - init final
DEBUG     2022-11-26 18:42:09.276 - app.api:init_app - 日志系统已加载
INFO:     Started server process [9104]
INFO:     Waiting for application startup.
INFO      2022-11-26 18:42:09.353 - app.api:startup - 已开启定时任务
C:\Users\Charles\AppData\Local\Programs\Python\Python311\Lib\site-packages\apscheduler\util.py:436: PytzUsageWarning: The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  return tzinfo.localize(dt)
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
INFO:     192.168.1.1:38644 - "GET /channel3.m3u8?fid=4gtv-live114&hd=1080 HTTP/1.1" 422 Unprocessable Entity
INFO:     192.168.1.1:38646 - "GET /channel3.m3u8?fid=4gtv-live114&hd=1080 HTTP/1.1" 422 Unprocessable Entity
INFO:     192.168.1.1:38650 - "GET /channel3.m3u8?fid=4gtv-live114&hd=1080 HTTP/1.1" 422 Unprocessable Entity
INFO:     192.168.1.1:38652 - "GET /channel3.m3u8?fid=4gtv-live114&hd=1080 HTTP/1.1" 422 Unprocessable Entity
INFO:     192.168.1.1:38656 - "GET /channel.m3u8?fid=4gtv-live114&hd=1080 HTTP/1.1" 422 Unprocessable Entity
INFO:     192.168.1.1:38658 - "GET /channel.m3u8?fid=4gtv-live114&hd=1080 HTTP/1.1" 422 Unprocessable Entity
INFO:     192.168.1.1:38664 - "GET /channel.m3u8?fid=4gtv-live114&hd=1080 HTTP/1.1" 422 Unprocessable Entity
INFO:     192.168.1.1:38666 - "GET /channel.m3u8?fid=4gtv-live114&hd=1080 HTTP/1.1" 422 Unprocessable Entity
INFO:     192.168.1.1:38674 - "GET /channel2.m3u8?fid=4gtv-live114&hd=1080 HTTP/1.1" 422 Unprocessable Entity

剛測試了
有重新 git clone https://github.com/239144498/Streaming-Media-Server-Pro.git 下全新的
依賴也安裝了 pip install -r requirements.txt
一樣出現的錯誤訊息

**Comment by charles0568** [comment]
INFO:     192.168.1.1:34248 - "GET /live/pool/4gtv-4gtv002/4gtv-live-mid/4gtv-4gtv002-avc1_2000000%3D3-mp4a_131000%3D7-begin%3D2494120490666666-dur%3D40000000-seq%3D62353010.ts?token=fUL1x7HmnMef_dhghFgHAw&expires=1669490253&token1=5KMTMhBEpXzuVBFjdHbOvQ&expires1=1669490253&refer=NDA5NTUwMjItMWFlMS00NGQ1LWI5M2EtODJmNDMxY2ZlYmYx&y=0 HTTP/1.1" 200 OK
INFO:     192.168.1.1:34248 - "GET /live/pool/4gtv-4gtv002/4gtv-live-mid/4gtv-4gtv002-avc1_2000000%3D3-mp4a_131000%3D7-begin%3D2494120530666666-dur%3D40000000-seq%3D62353011.ts?token=fUL1x7HmnMef_dhghFgHAw&expires=1669490253&token1=5KMTMhBEpXzuVBFjdHbOvQ&expires1=1669490253&refer=NDA5NTUwMjItMWFlMS00NGQ1LWI5M2EtODJmNDMxY2ZlYmYx&y=0 HTTP/1.1" 200 OK
INFO:     192.168.1.1:34248 - "GET /live/pool/4gtv-4gtv002/4gtv-live-mid/4gtv-4gtv002-avc1_2000000%3D3-mp4a_131000%3D7-begin%3D2494120570666666-dur%3D40000000-seq%3D62353012.ts?token=fUL1x7HmnMef_dhghFgHAw&expires=1669490253&token1=5KMTMhBEpXzuVBFjdHbOvQ&expires1=1669490253&refer=NDA5NTUwMjItMWFlMS00NGQ1LWI5M2EtODJmNDMxY2ZlYmYx&y=0 HTTP/1.1" 200 OK
SUCCESS   2022-11-27 01:10:00.003 - app.plugins.a4gtv.tasks:filetask - 成功删除视频文件0个
INFO:     192.168.1.1:34562 - "GET /channel2.m3u8?fid=4gtv-4gtv049&hd=1080 HTTP/1.1" 302 Found
INFO:     192.168.1.1:34562 - "GET /channel.m3u8?fid=4gtv-4gtv049&hd=Clarity.h&host=https://4gtvfreepc-cds.cdn.hinet.net HTTP/1.1" 422 Unprocessable Entity
INFO:     192.168.1.1:34564 - "GET /channel.m3u8?fid=4gtv-4gtv049&hd=Clarity.h&host=https://4gtvfreepc-cds.cdn.hinet.net HTTP/1.1" 422 Unprocessable Entity
INFO:     192.168.1.1:34576 - "GET /channel2.m3u8?fid=4gtv-4gtv076&hd=1080 HTTP/1.1" 302 Found
INFO:     192.168.1.1:34576 - "GET /channel.m3u8?fid=4gtv-4gtv076&hd=Clarity.h&host=https://4gtvfreepc-cds.cdn.hinet.net HTTP/1.1" 422 Unprocessable Entity
INFO:     192.168.1.1:34578 - "GET /channel.m3u8?fid=4gtv-4gtv076&hd=Clarity.h&host=https://4gtvfreepc-cds.cdn.hinet.net HTTP/1.1" 422 Unprocessable Entity
SUCCESS   2022-11-27 01:10:23.619 - app.plugins.a4gtv.endecrypt:get4gtvurl - 4gtv-4gtv017 200
INFO:     192.168.1.1:34598 - "GET /channel2.m3u8?fid=4gtv-4gtv017&hd=1080 HTTP/1.1" 302 Found
INFO:     192.168.1.1:34598 - "GET /channel.m3u8?fid=4gtv-4gtv017&hd=Clarity.h&host=https://4gtvfreepc-cds.cdn.hinet.net HTTP/1.1" 422 Unprocessable Entity
INFO:     192.168.1.1:34604 - "GET /channel.m3u8?fid=4gtv-4gtv017&hd=Clarity.h&host=https://4gtvfreepc-cds.cdn.hinet.net HTTP/1.1" 422 Unprocessable Entity
SUCCESS   2022-11-27 01:10:29.869 - app.plugins.a4gtv.endecrypt:get4gtvurl - 4gtv-live069 200
INFO:     192.168.1.1:34612 - "GET /channel3.m3u8?fid=4gtv-live069&hd=1080 HTTP/1.1" 307 Temporary Redirect
INFO:     192.168.1.1:34612 - "GET /channel3.m3u8?fid=4gtv-live069&hd=1080 HTTP/1.1" 307 Temporary Redirect
INFO:     192.168.1.1:34612 - "GET /channel3.m3u8?fid=4gtv-4gtv016&hd=1080 HTTP/1.1" 307 Temporary Redirect
INFO:     192.168.1.1:34648 - "GET /channel3.m3u8?fid=4gtv-4gtv016&hd=1080 HTTP/1.1" 307 Temporary Redirect
SUCCESS   2022-11-27 01:10:45.554 - app.plugins.a4gtv.endecrypt:get4gtvurl - 4gtv-live029 200
INFO:     192.168.1.1:34648 - "GET /channel3.m3u8?fid=4gtv-live029&hd=1080 HTTP/1.1" 307 Temporary Redirect
SUCCESS   2022-11-27 01:10:52.824 - app.plugins.a4gtv.endecrypt:get4gtvurl - 4gtv-live024 200


有些頻道會出現這些錯誤 有些是OK的～是否有些頻道還沒處理？？
