### ISSUE TITLE
请教mysql的问题

### ISSUE THREAD

**Issue by blueveryday** [239144498/Streaming-Media-Server-Pro#32]
版主能不能详细介绍一下mysql的用法？
我ubuntu系统，mysql安装好了，也改了root和123456789的密码，端口3306也打开了。
但是运行py的时候，总是报错。

# python3 main.py
2022-11-26 03:29:22.281 | INFO     | app.conf.config:<module>:61 - 配置加载中...
......
2022-11-26 03:29:23.798 | INFO     | app.conf.config:<module>:147 - 配置加载完成
2022-11-26 03:29:23.897 | INFO     | app.db.DBtools:<module>:15 - 正在检测数据库连接状态...
2022-11-26 03:29:23.897 | WARNING  | app.db.DBtools:connect_redis:34 - redis连接失败
2022-11-26 03:29:23.897 | WARNING  | app.db.DBtools:<module>:65 - defaultdb未配置mysql
2022-11-26 03:29:23.899 | SUCCESS  | app.plugins.a4gtv.utile:init:61 - init final
DEBUG     2022-11-26 03:29:23.923 - app.api:init_app - 日志系统已加载
INFO:     Started server process [68]
INFO:     Waiting for application startup.
/usr/local/lib/python3.10/dist-packages/tzlocal/unix.py:177: UserWarning: Can not find any timezone configuration, defaulting to UTC.
  warnings.warn("Can not find any timezone configuration, defaulting to UTC.")
INFO      2022-11-26 03:29:23.942 - app.api:startup - [<Job (id=affa4069cae14f3ca3502b559253b5e5 name=gotask)>, <Job (id=fd026d0dcb41469f928a71b87fb45d20 name=sqltask)>, <Job (id=1c59bee5ee264ec2b6cad8de29319fa3 name=filetask)>]
INFO      2022-11-26 03:29:23.942 - app.api:startup - 已开启定时任务
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
SUCCESS   2022-11-26 03:30:00.001 - app.plugins.a4gtv.tasks:filetask - 成功删除视频文件0个

**Comment by redrainl** [comment]
2022-11-26 03:29:23.897 | WARNING | app.db.DBtools::65 - defaultdb未配置mysql
提示挺清楚的，配置文件里的defaultdb默认是空的，要改成数据库（mysql），安装说明里有写。

**Comment by blueveryday** [comment]
> 2022-11-26 03:29:23.897 | WARNING | app.db.DBtools::65 - defaultdb未配置mysql 提示挺清楚的，配置文件里的defaultdb默认是空的，要改成数据库（mysql），安装说明里有写。

真心看不懂关于mysql的教程。

**Comment by blueveryday** [comment]
# python3 main.py
2022-11-26 04:06:56.362 | INFO     | app.conf.config:<module>:61 - 配置加载中...
......
2022-11-26 04:06:57.908 | INFO     | app.conf.config:<module>:147 - 配置加载完成
2022-11-26 04:06:58.001 | INFO     | app.db.DBtools:<module>:15 - 正在检测数据库连接状态...
2022-11-26 04:06:58.002 | WARNING  | app.db.DBtools:connect_redis:34 - redis连接失败
2022-11-26 04:06:58.003 | ERROR    | app.db.DBtools:<module>:59 - (1698, "Access denied for user 'root'@'localhost'")
2022-11-26 04:06:58.003 | ERROR    | app.db.DBtools:<module>:60 - mysql初始化表失败
2022-11-26 04:06:58.004 | ERROR    | app.db.DBtools:mysql_connect_test:48 - (1698, "Access denied for user 'root'@'localhost'")
2022-11-26 04:06:58.004 | ERROR    | app.db.DBtools:mysql_connect_test:49 - mysql连接失败
2022-11-26 04:06:58.006 | SUCCESS  | app.plugins.a4gtv.utile:init:61 - init final
DEBUG     2022-11-26 04:06:58.028 - app.api:init_app - 日志系统已加载
INFO:     Started server process [408]
INFO:     Waiting for application startup.
/usr/local/lib/python3.10/dist-packages/tzlocal/unix.py:177: UserWarning: Can not find any timezone configuration, defaulting to UTC.
  warnings.warn("Can not find any timezone configuration, defaulting to UTC.")
INFO      2022-11-26 04:06:58.046 - app.api:startup - [<Job (id=9d780cb9611d4e3ea17e8dbbe37ab03e name=gotask)>, <Job (id=0c228060a5c34114b1ec68a8ce0ef1b6 name=sqltask)>, <Job (id=5fcc80dfe2204437a5fc5775fef20a15 name=filetask)>]
INFO      2022-11-26 04:06:58.047 - app.api:startup - 已开启定时任务
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)

**Comment by blueveryday** [comment]
版主，你好。
没有安装mysql，dokcer无法播放节目。
能不能在docker里面集成mysql服务，你的这个代码安装一直不成功，按照教程，数据库走不通。

**Comment by blueveryday** [comment]
root@f517b5d8595f:/code# python3 main.py
2022-11-26 15:07:38.394 | INFO     | app.conf.config:<module>:61 - 配置加载中...
......
2022-11-26 15:07:41.361 | INFO     | app.conf.config:<module>:147 - 配置加载完成
2022-11-26 15:07:41.448 | INFO     | app.db.DBtools:<module>:15 - 正在检测数据库连接状态...
2022-11-26 15:07:41.449 | WARNING  | app.db.DBtools:connect_redis:34 - redis连接失败
2022-11-26 15:07:41.451 | ERROR    | app.db.DBtools:<module>:59 - (1698, "Access denied for user 'root'@'localhost'")
2022-11-26 15:07:41.451 | ERROR    | app.db.DBtools:<module>:60 - mysql初始化表失败
2022-11-26 15:07:41.452 | ERROR    | app.db.DBtools:mysql_connect_test:48 - (1698, "Access denied for user 'root'@'localhost'")
2022-11-26 15:07:41.452 | ERROR    | app.db.DBtools:mysql_connect_test:49 - mysql连接失败
2022-11-26 15:07:41.454 | SUCCESS  | app.plugins.a4gtv.utile:init:61 - init final
DEBUG     2022-11-26 15:07:41.478 - app.api:init_app - 日志系统已加载
INFO:     Started server process [986]
INFO:     Waiting for application startup.
INFO      2022-11-26 15:07:41.497 - app.api:startup - [<Job (id=9aca30c3554b48a2829bcdaa80af2da0 name=gotask)>, <Job (id=3627f369721741c1893387c90566cc05 name=sqltask)>, <Job (id=9e5a35298b2d4d3eacad175a22b44a16 name=filetask)>]
INFO      2022-11-26 15:07:41.498 - app.api:startup - 已开启定时任务
/usr/local/lib/python3.10/dist-packages/apscheduler/util.py:436: PytzUsageWarning: The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  return tzinfo.localize(dt)
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
INFO:     172.17.0.1:56044 - "GET /docs HTTP/1.1" 200 OK
INFO:     172.17.0.1:56044 - "GET /openapi.json HTTP/1.1" 200 OK

**Comment by blueveryday** [comment]
还是报错。

**Comment by kfcx** [comment]
2022-11-26 15:07:41.452 | ERROR | app.db.DBtools:mysql_connect_test:48 - (1698, "Access denied for user 'root'@'localhost'")
日志提示mysql连接出错，查看解决方法 https://stackoverflow.com/questions/41645309/mysql-error-access-denied-for-user-rootlocalhost

你发的日志都是正常日志提示，没连接mysql也可以正常播放节目，不影响使用。

**Comment by blueveryday** [comment]
> 

但是我这边确实无法播放，任何一种形式都播放不了。
奇怪了，要不然我也不纠结mysql的问题了。
怎么都播放不了，晕死。

**Comment by kfcx** [comment]
提供程序中有帮助的日志，你上面发的日志没有关键信息

**Comment by jackiezh** [comment]
我刚刚更新了最新版本，结果跑起来报错。详细日志：

| 2022-11-26 19:30:23.651 | INFO     | app.conf.config:<module>:67 - 配置加载中...
| 2022-11-26 19:30:25.484 | INFO     | app.conf.config:<module>:146 - 配置加载完成
| 2022-11-26 19:30:25.608 | INFO     | app.db.DBtools:<module>:15 - 正在检测数据库连接状态...
| 2022-11-26 19:30:25.610 | SUCCESS  | app.db.DBtools:connect_redis:30 - redis已连接
| 2022-11-26 19:30:25.612 | INFO     | app.db.dbMysql:init_database:82 - video表已存在
| 2022-11-26 19:30:25.612 | SUCCESS  | app.db.DBtools:<module>:57 - mysql已创建初始化表
| ....
| Traceback (most recent call last):
|   File "/usr/local/bin/uvicorn", line 8, in <module>
|     sys.exit(main())
|   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
|     return self.main(*args, **kwargs)
|   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1055, in main
|     rv = self.invoke(ctx)
|   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
|     return ctx.invoke(self.callback, **ctx.params)
|   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
|     return __callback(*args, **kwargs)
|   File "/usr/local/lib/python3.9/site-packages/uvicorn/main.py", line 404, in main
|     run(
|   File "/usr/local/lib/python3.9/site-packages/uvicorn/main.py", line 569, in run
|     server.run()
|   File "/usr/local/lib/python3.9/site-packages/uvicorn/server.py", line 60, in run
|     return asyncio.run(self.serve(sockets=sockets))
|   File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
|     return loop.run_until_complete(main)
|   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
|     return future.result()
|   File "/usr/local/lib/python3.9/site-packages/uvicorn/server.py", line 67, in serve
|     config.load()
|   File "/usr/local/lib/python3.9/site-packages/uvicorn/config.py", line 477, in load
|     self.loaded_app = import_from_string(self.app)
|   File "/usr/local/lib/python3.9/site-packages/uvicorn/importer.py", line 21, in import_from_string
|     module = importlib.import_module(module_str)
|   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
|     return _bootstrap._gcd_import(name[level:], package, level)
|   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
|   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
|   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
|   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
|   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
|   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
|   File "/code/./app/main.py", line 7, in <module>
|     from app.api import app
|   File "/code/./app/api/__init__.py", line 19, in <module>
|     from app.plugins.a4gtv.tasks import gotask, sqltask, filetask
|   File "/code/./app/plugins/a4gtv/tasks.py", line 12, in <module>
|     from app.plugins.a4gtv.utile import get
|   File "/code/./app/plugins/a4gtv/utile.py", line 17, in <module>
|     from app.db.DBtools import redisState, cur, DBconnect
|   File "/code/./app/db/DBtools.py", line 61, in <module>
|     DBconnect, sqlState = mysql_connect_test()
|   File "/code/./app/db/DBtools.py", line 43, in mysql_connect_test
|     print(DBconnect.ping())
| AttributeError: 'MySQLConnect' object has no attribute 'ping'
| 2022-11-26 19:30:26.672 | INFO     | app.conf.config:<module>:67 - 配置加载中...

**Comment by kfcx** [comment]
已修复该问题，pull新版解决
