### ISSUE TITLE
新版2.6 已重新git 下來 有些頻道可以 大部分都無法解析成功 附上錯誤訊息

### ISSUE THREAD

**Issue by charles0568** [239144498/Streaming-Media-Server-Pro#33]
INFO:     192.168.1.1:44676 - "GET /live/pool/4gtv-4gtv002/4gtv-live-mid/4gtv-4gtv002-avc1_2000000%3D3-mp4a_131000%3D7-begin%3D2494480040666666-dur%3D40000000-seq%3D62361998.ts?token=SDVd8TCtz-vx5KfYXV6DAQ&expires=1669530198&token1=SJd75CozP8iz88kmVneKQA&expires1=1669530198&refer=MjkxNzZlNWItZTg0NS00OGIzLTk0YzQtZTZmMDZmMTBjMTEz&y=0 HTTP/1.1" 200 OK
INFO:     192.168.1.1:44676 - "GET /live/pool/4gtv-4gtv002/4gtv-live-mid/4gtv-4gtv002-avc1_2000000%3D3-mp4a_131000%3D7-begin%3D2494480080666666-dur%3D40000000-seq%3D62361999.ts?token=SDVd8TCtz-vx5KfYXV6DAQ&expires=1669530198&token1=SJd75CozP8iz88kmVneKQA&expires1=1669530198&refer=MjkxNzZlNWItZTg0NS00OGIzLTk0YzQtZTZmMDZmMTBjMTEz&y=0 HTTP/1.1" 200 OK
SUCCESS   2022-11-27 11:07:41.121 - app.plugins.a4gtv.utile:generatem3u8 - 4gtv-4gtv002 m3u8 generated successfully
INFO:     192.168.1.1:44676 - "GET /channel.m3u8?fid=4gtv-4gtv002&hd=1080 HTTP/1.1" 200 OK
INFO:     192.168.1.1:44676 - "GET /live/pool/4gtv-4gtv002/4gtv-live-mid/4gtv-4gtv002-avc1_2000000%3D3-mp4a_131000%3D7-begin%3D2494480120666666-dur%3D40000000-seq%3D62362000.ts?token=SDVd8TCtz-vx5KfYXV6DAQ&expires=1669530198&token1=SJd75CozP8iz88kmVneKQA&expires1=1669530198&refer=MjkxNzZlNWItZTg0NS00OGIzLTk0YzQtZTZmMDZmMTBjMTEz&y=0 HTTP/1.1" 200 OK
SUCCESS   2022-11-27 11:07:51.525 - app.plugins.a4gtv.endecrypt:get4gtvurl - litv-ftv09 200
INFO:     192.168.1.1:44766 - "GET /channel3.m3u8?fid=litv-ftv09&hd=1080 HTTP/1.1" 307 Temporary Redirect
SUCCESS   2022-11-27 11:07:57.088 - app.plugins.a4gtv.endecrypt:get4gtvurl - 4gtv-live046 200
INFO:     192.168.1.1:44766 - "GET /channel3.m3u8?fid=4gtv-live046&hd=1080 HTTP/1.1" 307 Temporary Redirect
INFO:     192.168.1.1:44866 - "GET /channel2.m3u8?fid=4gtv-4gtv049&hd=1080 HTTP/1.1" 302 Found
INFO:     192.168.1.1:44866 - "GET /channel.m3u8?fid=4gtv-4gtv049&hd=Clarity.h&host=https://4gtvfreepc-cds.cdn.hinet.net HTTP/1.1" 422 Unprocessable Entity
INFO:     192.168.1.1:44868 - "GET /channel.m3u8?fid=4gtv-4gtv049&hd=Clarity.h&host=https://4gtvfreepc-cds.cdn.hinet.net HTTP/1.1" 422 Unprocessable Entity
INFO:     192.168.1.1:44870 - "GET /channel2.m3u8?fid=4gtv-4gtv049&hd=1080 HTTP/1.1" 302 Found
INFO:     192.168.1.1:44870 - "GET /channel.m3u8?fid=4gtv-4gtv049&hd=Clarity.h&host=https://4gtvfreepc-cds.cdn.hinet.net HTTP/1.1" 422 Unprocessable Entity
INFO:     192.168.1.1:44872 - "GET /channel.m3u8?fid=4gtv-4gtv049&hd=Clarity.h&host=https://4gtvfreepc-cds.cdn.hinet.net HTTP/1.1" 422 Unprocessable Entity
SUCCESS   2022-11-27 11:09:13.176 - app.plugins.a4gtv.endecrypt:get4gtvurl - litv-longturn20 200
INFO:     118.169.143.63:38028 - "GET /channel3.m3u8?fid=litv-longturn20&hd=1080 HTTP/1.1" 307 Temporary Redirect
SUCCESS   2022-11-27 11:09:46.062 - app.plugins.a4gtv.endecrypt:get4gtvurl - 4gtv-live024 200
INFO:     118.169.143.63:38136 - "GET /channel3.m3u8?fid=4gtv-live024&hd=1080 HTTP/1.1" 307 Temporary Redirect

另外想問一下～有沒有支付寶可以掃碼讓我請您喝杯咖啡？

**Comment by kfcx** [comment]
该问题已修复；二维码已更新，感谢你的支持！

**Comment by charles0568** [comment]
剛試了一下～channel.m3u8和online沒問題～ 試了 channel2 和 channel3 就沒辦法了～
另外我可能在國外掃碼無法請您喝咖啡 寫只支持境內收款帳戶 可否直接給支付寶帳號 我好方便請您喝咖啡︿︿ 感謝您辛苦的debug 我的email是charles0568@gmail.com

**Comment by blueveryday** [comment]
> 剛試了一下～channel.m3u8和online沒問題～ 試了 channel2 和 channel3 就沒辦法了～ 目前測試在channel.m3u8裡 原住民電視台 4gtv-live014 Amc最愛電影 4gtv-4gtv017 這2個無法解析 -62365469.ts?token=9Az_b_vQxWVG5zkvPUL7Xw&expires=1669547134&token1=uk0tEZrVyO7CaCe2xVwNhA&expires1=1669547134&refer=ZDgwYWUxNWItZWU3Ni00OGRmLTg5ZTctNzJkYzRmMGI3ZWZi&y=0 HTTP/1.1" 200 OK INFO: 192.168.1.1:52122 - "GET /channel.m3u8?fid=4gtv-live014&hd=1080 HTTP/1.1" 404 Not Found INFO: 192.168.1.1:52124 - "GET /channel.m3u8?fid=4gtv-live014&hd=1080 HTTP/1.1" 404 Not Found
> 
> INFO: 192.168.1.1:52138 - "GET /channel.m3u8?fid=4gtv-4gtv017&hd=Clarity.h&host=https://4gtvfreepc-cds.cdn.hinet.net HTTP/1.1" 422 Unprocessable Entity INFO: 192.168.1.1:52140 - "GET /channel.m3u8?fid=4gtv-4gtv017&hd=Clarity.h&host=https://4gtvfreepc-cds.cdn.hinet.net HTTP/1.1" 422 Unprocessable Entity
> 
> 另外我可能在國外掃碼無法請您喝咖啡 寫只支持境內收款帳戶 可否直接給支付寶帳號 我好方便請您喝咖啡︿︿ 感謝您辛苦的debug 我的email是[charles0568@gmail.com](mailto:charles0568@gmail.com)

我死活用不起，搞不懂。

**Comment by kfcx** [comment]
> 剛試了一下～channel.m3u8和online沒問題～ 試了 channel2 和 channel3 就沒辦法了～ 目前測試在channel.m3u8裡 原住民電視台 4gtv-live014 Amc最愛電影 4gtv-4gtv017 這2個無法解析 -62365469.ts?token=9Az_b_vQxWVG5zkvPUL7Xw&expires=1669547134&token1=uk0tEZrVyO7CaCe2xVwNhA&expires1=1669547134&refer=ZDgwYWUxNWItZWU3Ni00OGRmLTg5ZTctNzJkYzRmMGI3ZWZi&y=0 HTTP/1.1" 200 OK INFO: 192.168.1.1:52122 - "GET /channel.m3u8?fid=4gtv-live014&hd=1080 HTTP/1.1" 404 Not Found INFO: 192.168.1.1:52124 - "GET /channel.m3u8?fid=4gtv-live014&hd=1080 HTTP/1.1" 404 Not Found
> 
> INFO: 192.168.1.1:52138 - "GET /channel.m3u8?fid=4gtv-4gtv017&hd=Clarity.h&host=https://4gtvfreepc-cds.cdn.hinet.net HTTP/1.1" 422 Unprocessable Entity INFO: 192.168.1.1:52140 - "GET /channel.m3u8?fid=4gtv-4gtv017&hd=Clarity.h&host=https://4gtvfreepc-cds.cdn.hinet.net HTTP/1.1" 422 Unprocessable Entity
> 
> 另外我可能在國外掃碼無法請您喝咖啡 寫只支持境內收款帳戶 可否直接給支付寶帳號 我好方便請您喝咖啡︿︿ 感謝您辛苦的debug 我的email是[charles0568@gmail.com](mailto:charles0568@gmail.com)

那个问题修复后需要重启服务更新

**Comment by 239144498** [comment]
> 

报错信息发一下，我帮你排查一下错误

**Comment by kfcx** [comment]
> > 剛試了一下～channel.m3u8和online沒問題～ 試了 channel2 和 channel3 就沒辦法了～ 目前測試在channel.m3u8裡 原住民電視台 4gtv-live014 Amc最愛電影 4gtv-4gtv017 這2個無法解析 -62365469.ts?token=9Az_b_vQxWVG5zkvPUL7Xw&expires=1669547134&token1=uk0tEZrVyO7CaCe2xVwNhA&expires1=1669547134&refer=ZDgwYWUxNWItZWU3Ni00OGRmLTg5ZTctNzJkYzRmMGI3ZWZi&y=0 HTTP/1.1" 200 OK INFO: 192.168.1.1:52122 - "GET /channel.m3u8?fid=4gtv-live014&hd=1080 HTTP/1.1" 404 Not Found INFO: 192.168.1.1:52124 - "GET /channel.m3u8?fid=4gtv-live014&hd=1080 HTTP/1.1" 404 Not Found
> > INFO: 192.168.1.1:52138 - "GET /channel.m3u8?fid=4gtv-4gtv017&hd=Clarity.h&host=https://4gtvfreepc-cds.cdn.hinet.net HTTP/1.1" 422 Unprocessable Entity INFO: 192.168.1.1:52140 - "GET /channel.m3u8?fid=4gtv-4gtv017&hd=Clarity.h&host=https://4gtvfreepc-cds.cdn.hinet.net HTTP/1.1" 422 Unprocessable Entity
> > 另外我可能在國外掃碼無法請您喝咖啡 寫只支持境內收款帳戶 可否直接給支付寶帳號 我好方便請您喝咖啡︿︿ 感謝您辛苦的debug 我的email是[charles0568@gmail.com](mailto:charles0568@gmail.com)
> 
> 我死活用不起，搞不懂。

报错信息发一下，我帮你排查一下错误

**Comment by maiacg** [comment]
channel2.m3u8?fid=4gtv-4gtv049&hd=1080 是错误的 正确是channel2.m3u8?fid=4gtv-4gtv049 不带&hd=1080

**Comment by kfcx** [comment]
> 

这个带参问题pull最新版解决

**Comment by charles0568** [comment]
好棒！！等一下重拉！謝謝您！！
