### ISSUE TITLE
 generate_url 函数报错

### ISSUE THREAD

**Issue by jin38324** [239144498/Streaming-Media-Server-Pro#35]
File "/code/./app/plugins/a4gtv/utile.py", line 224, in backtasklocal
    herf = generate_url(fid, host, hd, begin + (i * get.para[fid]['a7']), seq + i, url)
TypeError: generate_url() takes 5 positional arguments but 6 were given

需要去掉hd参数

**Comment by kfcx** [comment]
感谢反馈，问题已修复
