### ISSUE TITLE
請問斷流問題～有方法可改善嗎？

### ISSUE THREAD

**Issue by charles0568** [239144498/Streaming-Media-Server-Pro#36]
大概看個幾分鐘後會斷流 過2～5秒才會再接上  試過online  channel  channel2 channel3 都是一樣 這様的斷流情形 有辦法改善嗎？

**Comment by kfcx** [comment]
这个问题我将在下一个版本做相应处理

**Comment by charles0568** [comment]
好的～謝謝你～再麻煩您了～感謝～

**Comment by blueveryday** [comment]
> 

你网页上面很多台都没有了……

**Comment by kfcx** [comment]
> > 
> 
> 你网页上面很多台都没有了……

那些频道不符合社会主义核心价值观

**Comment by blueveryday** [comment]
> > > 
> > 
> > 
> > 你网页上面很多台都没有了……
> 
> 那些频道不符合社会主义核心价值观

没有必要吧。
