### ISSUE TITLE
docker版本

### ISSUE THREAD

**Issue by Yumega** [239144498/Streaming-Media-Server-Pro#37]
昨晚安装完可以观看，今天http://192.168.11.1:8080/docs 可以访问

但是节目 无法播放

下面这个可以一直播放 
docker run -d \
--name=YTBlive \
-e TZ=Asia/Shanghai \
-p 13080:8080 \ 
ghcr.io/jnewland/hlstube:latest

中天新闻，
http://192.168.11.1:13080/_QbRXRnHMVY

**Comment by 239144498** [comment]
已修复该问题，你需要重启服务
