### ISSUE TITLE
关于自定义清晰度无效

### ISSUE THREAD

**Issue by Gaoleiyu** [239144498/Streaming-Media-Server-Pro#40]
部署方式为docker简易部署，没有安装数据库。
最后参数不论为480/720/1080播放出来的视频均为720，请问是该参数失效了还是源就是720的呢

**Comment by Gaoleiyu** [comment]
又发现使用channel3可以1080，online&channel1&2都只能720。但是用了channel3就不走自己服务器流量了

**Comment by 239144498** [comment]
目前只提供720
