### ISSUE TITLE
很多頻道都無法解析～再麻煩修復了～謝謝

### ISSUE THREAD

**Issue by charles0568** [239144498/Streaming-Media-Server-Pro#41]
有些頻道都無法解析～再麻煩修復了～謝謝～
錯誤訊息如下
SUCCESS   2022-12-28 13:08:51.959 - app.plugins.a4gtv.endecrypt:get4gtvurl - 4gtv-4gtv002 404
WARNING   2022-12-28 13:11:59.191 - app.plugins.a4gtv.utile:updateonline - 未获得数据
SUCCESS   2022-12-28 13:10:00.002 - app.plugins.a4gtv.tasks:filetask - 成功删除视频文件0个
WARNING   2022-12-28 13:11:59.192 - app.plugins.a4gtv.utile:updateonline - 404, {"code":404,"msg":"请求失败","data":"Not found 4gtv-4gtv002"}
INFO:     192.168.1.1:53226 - "GET /channel2.m3u8?fid=4gtv-4gtv002&hd=1080 HTTP/1.1" 406 Not Acceptable
SUCCESS   2022-12-28 13:11:59.862 - app.plugins.a4gtv.endecrypt:get4gtvurl - 4gtv-4gtv002 404
WARNING   2022-12-28 13:11:59.865 - app.plugins.a4gtv.utile:updateonline - 未获得数据
WARNING   2022-12-28 13:11:59.866 - app.plugins.a4gtv.utile:updateonline - 404, {"code":404,"msg":"请求失败","data":"Not found 4gtv-4gtv002"}
INFO:     192.168.1.1:53316 - "GET /channel2.m3u8?fid=4gtv-4gtv002&hd=1080 HTTP/1.1" 406 Not Acceptable
SUCCESS   2022-12-28 13:12:00.183 - app.plugins.a4gtv.endecrypt:get4gtvurl - 4gtv-live008 404
WARNING   2022-12-28 13:12:00.185 - app.plugins.a4gtv.utile:updateonline - 未获得数据
WARNING   2022-12-28 13:12:00.186 - app.plugins.a4gtv.utile:updateonline - 404, {"code":404,"msg":"请求失败","data":"Not found 4gtv-live008"}
INFO:     192.168.1.1:53358 - "GET /channel2.m3u8?fid=4gtv-live008&hd=1080 HTTP/1.1" 406 Not Acceptable
SUCCESS   2022-12-28 13:12:00.496 - app.plugins.a4gtv.endecrypt:get4gtvurl - 4gtv-4gtv003 404
WARNING   2022-12-28 13:12:00.498 - app.plugins.a4gtv.utile:updateonline - 未获得数据
WARNING   2022-12-28 13:12:00.499 - app.plugins.a4gtv.utile:updateonline - 404, {"code":404,"msg":"请求失败","data":"Not found 4gtv-4gtv003"}
INFO:     192.168.1.1:53406 - "GET /channel2.m3u8?fid=4gtv-4gtv003&hd=1080 HTTP/1.1" 406 Not Acceptable
INFO:     192.168.1.1:53416 - "GET /channel2.m3u8?fid=4gtv-4gtv003&hd=1080 HTTP/1.1" 405 Method Not Allowed
INFO:     192.168.1.1:53424 - "GET /channel2.m3u8?fid=4gtv-4gtv003&hd=1080 HTTP/1.1" 405 Method Not Allowed
INFO:     192.168.1.1:53426 - "GET /channel2.m3u8?fid=4gtv-4gtv003&hd=1080 HTTP/1.1" 405 Method Not Allowed

**Comment by 239144498** [comment]
即刻起不再对外公开那些频道，如果需要观看可以联系邮箱[239144498@qq.com](mailto:239144498@qq.com)
