### ISSUE TITLE
拉黑IP是整个IP段拉黑吗？

### ISSUE THREAD

**Issue by Acris** [239144498/Streaming-Media-Server-Pro#42]
由于使用的软件APTV（[https://apps.apple.com/cn/app/aptv/id1630403500](https://apps.apple.com/cn/app/aptv/id1630403500)）会获取每个频道的延迟和预览图并且该功能无法关闭，所以会导致接口请求超限。

我已经修改程序添加了缓存和请求你API的rate limit，限制了5秒内只能请求一次，在稳定使用几天后IP还是被拉黑。重新换了IP后发现只要是同一个IP段的IP，仍然会提示拉黑，即使如 120.230.xxx.xxx和120.231.xxx.xxx这种只有最前面相同的也是提示拉黑。

所以请问下拉黑是否整个IP段都会拉黑以及是否会有自动解封机制？

另外建议从程序层面限制请求后端API的次数，避免因为正常使用也会因软件获取预览图等原因频繁请求而拉黑，这是我添加缓存和rate limit的一个例子：https://github.com/Acris/Streaming-Media-Server-Pro/blob/main/app/plugins/a4gtv/endecrypt.py#L19

另外：昨天被拉黑前，发现从program.m3u获取的频道数变为了37个，基本只剩一些儿童频道之内的，所以询问下是否不再提供其他频道了？

**Comment by 239144498** [comment]
所以请问下拉黑是否整个IP段都会拉黑以及是否会有自动解封机制？
1、拉黑只针对请求ip，不是整个ip段，自动解封机制未来会加入，可以邮箱联系我解封。

2、缓存和rate limit是一个不错的建议，欢迎PR。

3、即刻起不再对外公开那些频道，如果需要观看可以联系邮箱[239144498@qq.com](mailto:239144498@qq.com)
