### ISSUE TITLE
config.py中gdata = None，导致生成频道列表出错

### ISSUE THREAD

**Issue by jin38324** [239144498/Streaming-Media-Server-Pro#43]
刚试用了最新版本，程序可以启动，但是生成频道列表出错。
原因是config.py中 `gdata = None`，导致生成频道列表出错。
请问这是bug？还是`/program.m3u`接口弃用了？
![4361b841c1d813d1d29051a82d65ad2](https://user-images.githubusercontent.com/52519003/210495099-c25ea8c3-2c3c-4d71-8547-604b9a29b63b.png)

**Comment by kfcx** [comment]
该接口不再支持,代理功能可以正常使用
