### ISSUE TITLE
请求成功,无法打开链接

### ISSUE THREAD

**Issue by zyjia** [239144498/Streaming-Media-Server-Pro#45]
部署是最新的docker,
请求 http://192.168.10.1:8081/channel.m3u8?fid=4gtv003,返回{"code":404,"msg":"请求成功","data":"Not found 4gtv003"}，用代码运行也是同样的错误,应该是少了idata数据,请帮忙解决，谢谢了。

**Comment by kfcx** [comment]
部分接口不再支持,代理功能可以正常使用
