### ISSUE TITLE
请教大佬一下

### ISSUE THREAD

**Issue by yyxiaofeng** [239144498/Streaming-Media-Server-Pro#48]
请问下大佬，像这种足球4K源，http://live.iptvtotaal.com:8000/awpreneniptv/09HZaVeOmh/20560，为啥用Potplay播放一会就会重复前面的画面几秒，或者卡顿跳帧呢？有没有解决办法呢

**Comment by kfcx** [comment]
我尝试了但无法打开改源，可以发到我邮箱收信更及时

**Comment by orency** [comment]
这个源是hevc 4k main10 50帧 高码的，应该是你用的设备gpu不支持硬解该码流，用的软解，然后cpu性能垃圾软解卡顿导致的。办法就是升级观看设备

**Comment by yyxiaofeng** [comment]
那用你的Streaming-Media-Server-Pro可以流畅观看吗？

**Comment by kfcx** [comment]
> 这个源是hevc 4k main10 50帧 高码的，应该是你用的设备gpu不支持硬解该码流，用的软解，然后cpu性能垃圾软解卡顿导致的。办法就是升级观看设备

重新尝试可以正常播放，你遇到的问题是代理频道后出现的吗还是不代理出现的?

**Comment by kfcx** [comment]
> 

理论可以流畅观看，主要受网络带宽影响。
